{{- $_ := set .Values "comp" .Values.crontinuous -}}
{{- if .Values.comp.enabled }}
{{- include "common-manifests" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crontinuous.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/name: crontinuous
spec:
  {{- if kindIs "int64" .Values.comp.replicaCount }}
  replicas: {{ .Values.comp.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "vulcan.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: crontinuous
  template:
    metadata:
      labels: {{- include "vulcan.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/name: crontinuous
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/crontinuous/secrets.yaml") . | sha256sum }}
        {{- include "common-annotations" . | nindent 8 }}
        {{- with .Values.comp.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- include "common-spec" . | nindent 6 }}
    {{- with .Values.comp.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.comp.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        {{- include "common-containers" . | nindent 8}}
        - name: {{ .Values.comp.name }}
          {{- with .Values.comp.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.comp.image.repository }}:{{ .Values.comp.image.tag }}"
          imagePullPolicy: {{ .Values.comp.image.pullPolicy }}
          env:
          - name: PORT
            value: {{ .Values.comp.containerPort | quote }}
          - name: AWS_REGION
            value: {{ .Values.comp.conf.region | default (include "region" .) }}
          - name: CRONTINUOUS_BUCKET
            value: {{ .Values.comp.conf.crontinuousBucket }}
          - name: VULCAN_API
            value: {{ .Values.comp.conf.vulcanApi | default (include "api.url" .) }}
          - name: VULCAN_USER
            value: {{ .Values.comp.conf.vulcanUser }}
          - name: ENABLE_TEAMS_WHITELIST_SCAN
            value: {{ .Values.comp.conf.enableTeamsWhitelistScan | quote }}
          - name: TEAMS_WHITELIST_SCAN
            value: {{ .Values.comp.conf.teamsWhitelistScan | quote}}
          - name: ENABLE_TEAMS_WHITELIST_REPORT
            value: {{ .Values.comp.conf.enableTeamsWhitelistReport | quote }}
          - name: TEAMS_WHITELIST_REPORT
            value: {{ .Values.comp.conf.teamsWhitelistReport | quote }}
        {{- include "common-envs" . | nindent 10 }}
        {{- range $name, $value := .Values.comp.extraEnv }}
          - name: {{ $name }}
            value: {{ $value | quote }}
        {{- end }}
          envFrom:
          - secretRef:
              name: {{ include "crontinuous.fullname" . }}
          ports:
            - name: {{ include "common-appPortName" . }}
              containerPort: {{ .Values.comp.containerPort }}
              protocol: TCP
          {{- include "common-lifecycle" . | nindent 10 }}
          {{- with .Values.comp.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
      {{- include "common-volumes" . | nindent 6}}
      {{- with .Values.comp.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.comp.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.comp.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
