{{- $_ := set .Values "comp" .Values.crontinuous -}}
{{- if .Values.comp.enabled }}
{{- include "common-manifests" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "comp.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.comp.name }}
spec:
  {{- if kindIs "int64" .Values.comp.replicaCount }}
  replicas: {{ .Values.comp.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "vulcan.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: {{ .Values.comp.name }}
  template:
    metadata:
      labels: {{- include "vulcan.podLabels" . | nindent 8 }}
        app.kubernetes.io/name: {{ .Values.comp.name }}
      annotations:
        checksum/secrets: {{ include "crontinuous-secrets" . | sha256sum }}
        {{- include "common-annotations" . | nindent 8 }}
    spec:
      containers:
        {{- include "common-deployment-sidecars" . | nindent 8 }}
        - name: {{ .Values.comp.name }}
          {{- include "common-container" . | nindent 10 }}
          env:
          - name: PORT
            value: {{ .Values.comp.containerPort | quote }}
          - name: AWS_REGION
            value: {{ .Values.comp.conf.region | default (include "region" .) }}
          - name: CRONTINUOUS_BUCKET
            value: {{ .Values.comp.conf.crontinuousBucket }}
          - name: VULCAN_API
            value: {{ .Values.comp.conf.vulcanApi | default (include "api.url" .) }}
          - name: VULCAN_USER
            value: {{ .Values.comp.conf.vulcanUser }}
          - name: ENABLE_TEAMS_WHITELIST_SCAN
            value: {{ .Values.comp.conf.enableTeamsWhitelistScan | quote }}
          - name: TEAMS_WHITELIST_SCAN
            value: {{ .Values.comp.conf.teamsWhitelistScan | quote }}
          - name: ENABLE_TEAMS_WHITELIST_REPORT
            value: {{ .Values.comp.conf.enableTeamsWhitelistReport | quote }}
          - name: TEAMS_WHITELIST_REPORT
            value: {{ .Values.comp.conf.teamsWhitelistReport | quote }}
        {{- include "common-container-envs" . | nindent 10 }}
          envFrom:
          - secretRef:
              name: {{ include "comp.fullname" . }}
          ports:
            - name: {{ include "common-appPortName" . }}
              containerPort: {{ .Values.comp.containerPort }}
              protocol: TCP
      volumes:
      {{- include "common-deployment-volumes" . | nindent 6 }}
    {{- include "common-deployment-spec" . | nindent 6 }}
{{- end }}
