{{- $_ := (set .Values "comp" .Values.crontinuous) -}}
{{- if and .Values.comp.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crontinuous.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
type: Opaque
data:
  VULCAN_TOKEN: {{ .Values.comp.conf.vulcanToken | b64enc | quote }}
{{- end }}
