{{- $c := (dict "comp" .Values.crontinuous "context" $) -}}
{{- if and $c.comp.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crontinuous.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/name: crontinuous
type: Opaque
data:
  VULCAN_TOKEN: {{ $c.comp.conf.vulcanToken | b64enc | quote }}
{{- end }}
