{{/*
Override names
*/}}
{{- define "common-hpa" -}}
{{- if and .Values.comp.enabled .Values.comp.autoscaling.enabled -}}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "vulcan.fullname" . }}-{{ .Values.comp.name }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "vulcan.fullname" . }}-{{ .Values.comp.name }}
  minReplicas: {{ .Values.comp.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.comp.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.comp.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.comp.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.comp.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.comp.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end -}}
{{- end -}}
