{{/*
Override names
*/}}
{{- define "common-hpa" -}}
{{- if and .Values.comp.enabled .Values.comp.autoscaling.enabled -}}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "vulcan.fullname" . }}-{{ .Values.comp.name }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.comp.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "vulcan.fullname" . }}-{{ .Values.comp.name }}
  minReplicas: {{ .Values.comp.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.comp.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.comp.autoscaling.targetCPUUtilizationPercentage }}
{{- end -}}
{{- end -}}
