{{/*
Override names
*/}}
{{- define "common-hpa" -}}
{{- if and .Values.comp.enabled .Values.comp.autoscaling.enabled -}}
{{- if semverCompare "<1.23-0" (include "common.capabilities.kubeVersion" .) }}
apiVersion: autoscaling/v2beta1
{{- else }}
apiVersion: autoscaling/v2
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include  "comp.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.comp.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include  "comp.fullname" . }}
  minReplicas: {{ .Values.comp.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.comp.autoscaling.maxReplicas }}
  {{- if semverCompare ">=1.23-0" (include "common.capabilities.kubeVersion" .) }}
  {{- with .Values.comp.autoscaling.behavior }}
  behavior: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  metrics:
    {{- if .Values.comp.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        {{- if semverCompare "<1.23-0" (include "common.capabilities.kubeVersion" .) }}
        targetAverageUtilization: {{ .Values.comp.autoscaling.targetCPUUtilizationPercentage }}
        {{- else }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.comp.autoscaling.targetCPUUtilizationPercentage }}
        {{- end }}
    {{- end }}
    {{- if .Values.comp.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        {{- if semverCompare "<1.23-0" (include "common.capabilities.kubeVersion" .) }}
        targetAverageUtilization: {{ .Values.comp.autoscaling.targetMemoryUtilizationPercentage }}
        {{- else }}
        target:
          type: Utilization
          averageUtilization: {{ .Values.comp.autoscaling.targetMemoryUtilizationPercentage }}
        {{- end }}
    {{- end }}
{{- end -}}
{{- end -}}
