{{/*
Override names
*/}}
{{- define "common-ingress" -}}
{{- if and .Values.comp.enabled .Values.comp.ingress.enabled -}}
{{- $fullName := printf "%s-%s" (include "vulcan.fullname" . ) .Values.comp.name -}}
{{- $svcPort := .Values.comp.service.port -}}
{{- if and .Values.comp.ingress.className (not (semverCompare ">=1.18-0" (include "common.capabilities.kubeVersion" .))) }}
  {{- if not (hasKey .Values.comp.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.comp.ingress.annotations "kubernetes.io/ingress.class" .Values.comp.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" (include "common.capabilities.kubeVersion" .) -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" (include "common.capabilities.kubeVersion" .) -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.comp.name }}
  {{- with .Values.comp.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.comp.ingress.className (semverCompare ">=1.18-0" (include "common.capabilities.kubeVersion" .)) }}
  ingressClassName: {{ .Values.comp.ingress.className }}
  {{- end }}
  {{- if .Values.comp.ingress.tls }}
  tls:
    {{- range .Values.comp.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.comp.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          {{- if kindIs "string" . }}
          - path: {{ . }}
            {{- if semverCompare ">=1.18-0" (include "common.capabilities.kubeVersion" $) }}
            pathType: ImplementationSpecific
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" (include "common.capabilities.kubeVersion" $) }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- else }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" (include "common.capabilities.kubeVersion" $)) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" (include "common.capabilities.kubeVersion" $) }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
          {{- end }}
    {{- end }}
  {{- end }}
{{- end -}}
