{{/*
Override names
*/}}
{{- define "comp-ingress" -}}
{{- if and .comp.enabled .comp.ingress.enabled -}}
{{- $fullName := printf "%s-%s" (include "vulcan.fullname" .context ) .comp.name -}}
{{- $svcPort := .comp.service.port -}}
{{- if semverCompare ">=1.14-0" .context.Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels: {{- include "vulcan.labels" .context | nindent 4 }}
    app.kubernetes.io/name: {{ .comp.name }}
  {{- with .comp.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .comp.ingress.tls }}
  tls:
    {{- range .comp.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .comp.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
          {{- end }}
    {{- end }}
  {{- end }}
{{- end -}}
