{{/*
Override names
*/}}
{{- define "common-ingress" -}}
{{- if and .Values.comp.enabled .Values.comp.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "comp.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.comp.name }}
  {{- if .Values.comp.ingress.annotations }}
  annotations:
    {{- tpl (toYaml .Values.comp.ingress.annotations) . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.comp.ingress.className }}
  ingressClassName: {{ .Values.comp.ingress.className | quote }}
  {{- end }}
  rules:
    - host: {{ include "ingress.hostname" . }}
      http:
        paths:
          {{- if .Values.comp.ingress.extraPaths }}
          {{- toYaml .Values.comp.ingress.extraPaths | nindent 10 }}
          {{- end }}
          - path: {{ .Values.comp.ingress.path | default "/" }}
            pathType: {{ .Values.comp.ingress.pathType | default "ImplementationSpecific" }}
            backend:
              service:
                name: {{ include "comp.fullname" . }}
                port:
                  number: {{ .Values.comp.service.port }}
    {{- range .Values.comp.ingress.extraHosts }}
    - host: {{ tpl .name $ | quote }}
      http:
        paths:
          - path: {{ default "/" .path }}
            pathType: {{ default "ImplementationSpecific" .pathType }}
            backend:
              service:
                name: {{ include "comp.fullname" $ }}
                port:
                  number: {{ $.Values.comp.service.port }}
    {{- end }}
    {{- if .Values.comp.ingress.extraRules }}
    {{- tpl (toYaml .Values.comp.ingress.extraRules) . | nindent 4 }}
    {{- end }}
  {{- if or .Values.comp.ingress.tls .Values.comp.ingress.extraTls }}
  tls:
    {{- if .Values.comp.ingress.tls }}
    - hosts:
      - {{ include "ingress.hostname" . }}
      secretName: {{ .Values.comp.ingress.secretName | default (printf "%s-tls" (include "comp.fullname" . )) }}
    {{- end }}
    {{- if .Values.comp.ingress.extraTls }}
    {{- tpl (toYaml .Values.comp.ingress.extraTls) . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end -}}
{{- end -}}
