{{/*
Override names
*/}}
{{- define "comp-service" -}}
{{- if and .comp.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "vulcan.fullname" .context }}-{{ .comp.name }}
  labels: {{- include "vulcan.labels" .context | nindent 4 }}
    app.kubernetes.io/component: {{ .comp.name }}
spec:
  type: {{ .comp.service.type }}
  ports:
    - port: {{ .comp.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "vulcan.selectorLabels" .context | nindent 6 }}
      app.kubernetes.io/component: {{ .comp.name }}
{{- end -}}
{{- end -}}
