{{/*
Override names
*/}}
{{- define "comp-service" -}}
{{- if and .comp.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "vulcan.fullname" .context }}-{{ .comp.name }}
  labels: {{- include "vulcan.labels" .context | nindent 4 }}
    app.kubernetes.io/name: {{ .comp.name }}
spec:
  type: {{ .comp.service.type }}
  ports:
    - port: {{ .comp.service.port }}
      targetPort: {{ .comp.service.targetPort | default "http" }}
      protocol: {{ .comp.service.protocol | default "TCP" }}
      name: {{ .comp.service.portName | default "http" }}
  selector: {{- include "vulcan.selectorLabels" .context | nindent 6 }}
      app.kubernetes.io/name: {{ .comp.name }}
{{- end -}}
{{- end -}}
