apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/component: dogstatsd
  name: {{ .Release.Name }}-dogstatsd
type: Opaque
data:
  DD_API_KEY: {{ .Values.dogstatsd.apiKey | b64enc | quote }}
