apiVersion: v1
kind: Secret
metadata:
  labels:
    name: {{ include "vulcan.fullname" . }}-s3
  name: {{ include "vulcan.fullname" . }}-s3
type: Opaque
data:
  accesskey: {{ .Values.s3.accessKey | b64enc | quote }}
  secretkey: {{ .Values.s3.secretKey | b64enc | quote }}
