{{- $_ := (set .Values "comp" .Values.ui) -}}
{{- if .Values.comp.enabled }}
{{- include "common-manifests" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ui.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/name: ui
spec:
  {{- if kindIs "int64" .Values.comp.replicaCount }}
  replicas: {{ .Values.comp.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "vulcan.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: ui
  template:
    metadata:
      labels: {{- include "vulcan.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/name: ui
      annotations:
        {{- include "common-annotations" . | nindent 8 }}
        {{- with .Values.comp.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- include "common-spec" . | nindent 6 }}
    {{- with .Values.comp.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.comp.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        {{- include "common-containers" . | nindent 8}}
        - name: {{ .Values.comp.name }}
          {{- with .Values.comp.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.comp.image.repository }}:{{ .Values.comp.image.tag }}"
          imagePullPolicy: {{ .Values.comp.image.pullPolicy }}
          env:
          - name: PORT
            value: {{ .Values.comp.containerPort | quote }}
          - name: API_URL
            value: {{ .Values.comp.conf.apiUrl | quote }}
          - name: UI_DOCS_API_LINK
            value: {{ .Values.comp.conf.docs.apiLink | quote }}
          - name: UI_DOCS_WHITELISTING_LINK
            value: {{ .Values.comp.conf.docs.whitelistingLink | quote }}
          - name: UI_DOCS_DISCOVERY_LINK
            value: {{ .Values.comp.conf.docs.discoveryLink | quote }}
          - name: UI_DOCS_AUDITROLE_LINK
            value: {{ .Values.comp.conf.docs.auditRoleLink | quote }}
          - name: UI_CONTACT_EMAIL
            value: {{ .Values.comp.conf.contact.email | quote }}
          - name: UI_CONTACT_SLACK
            value: {{ .Values.comp.conf.contact.slack | quote }}
        {{- include "common-envs" . | nindent 10 }}
        {{- range $name, $value := .Values.comp.extraEnv }}
          - name: {{ $name }}
            value: {{ $value | quote }}
        {{- end }}
          ports:
            - name: {{ include "common-appPortName" . }}
              containerPort: {{ .Values.comp.containerPort }}
              protocol: TCP
          {{- include "common-lifecycle" . | nindent 10 }}
          {{- with .Values.comp.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
      {{- include "common-volumes" . | nindent 6}}
      {{- with .Values.comp.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.comp.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.comp.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
