{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "reportsgenerator.serviceAccountName" . }}
  labels:
{{ include "reportsgenerator.labels" . | nindent 4 }}
{{- end -}}
