apiVersion: v1
kind: Secret
metadata:
  labels:
    name: {{ include "stream.fullname" . }}
  name: {{ include "stream.fullname" . }}
type: Opaque
data:
  REDIS_PWD: {{ .Values.conf.redis.pwd | b64enc | quote }}
