{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "stream.serviceAccountName" . }}
  labels:
{{ include "stream.labels" . | indent 4 }}
{{- end -}}
