os: linux
dist: bionic
language: minimal
git:
  depth: false
before_script:
- curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
- curl -sL https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz | sudo tar xz -C /usr/local/bin kubeval
script: ./test.sh -f
