{{- $_ := (set .Values "comp" .Values.persistence) -}}
{{- if .Values.comp.enabled }}
{{- include "common-manifests" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "persistence.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/name: persistence
spec:
  {{- if kindIs "int64" .Values.comp.replicaCount }}
  replicas: {{ .Values.comp.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "vulcan.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: persistence
  template:
    metadata:
      labels: {{- include "vulcan.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/name: persistence
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/persistence/secrets.yaml") . | sha256sum }}
        {{- include "common-annotations" . | nindent 8 }}
        {{- with .Values.comp.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      initContainers:
        - name: waitfordb
          image: "{{ .Values.comp.waitfordb.image.repository }}:{{ .Values.comp.waitfordb.image.tag }}"
          imagePullPolicy: Always
          command: ['sh', '-c', 'until pg_isready -t 5; do echo WaitingDB; done;']
          env:
          - name: PGHOST
            value: {{ .Values.comp.db.host | default (include "postgresqlHost" .) | quote }}
          - name: PGPORT
            value: {{ .Values.comp.db.port | quote }}
      containers:
        {{- include "common-deployment-sidecars" . | nindent 8 }}
        - name: {{ .Values.comp.name }}
          {{- include "common-container" . | nindent 10 }}
          env:
          - name: PORT
            value: {{ .Values.comp.containerPort | quote }}
          - name: POSTGRES_DB
            value: {{ .Values.comp.db.name | quote }}
          - name: POSTGRES_HOST
            value: {{ .Values.comp.db.host | default (include "postgresqlHost" .) | quote }}
          - name: POSTGRES_PORT
            value: {{ .Values.comp.db.port | quote }}
          - name: POSTGRES_USER
            value: {{ .Values.comp.db.user | quote }}
          - name: POSTGRES_SSLMODE
            value: {{ .Values.comp.db.sslMode | quote }}
          {{- if .Values.comp.db.ca }}
          - name: POSTGRES_CA_B64
            value: {{ .Values.comp.db.ca | b64enc | quote }}
          {{- end }}
          - name: LOG_LEVEL
            value: {{ .Values.comp.conf.logLevel | quote }}
          - name: RAILS_MAX_THREADS
            value: {{ .Values.comp.conf.railsMaxThreads | quote }}
        {{- include "common-container-envs" . | nindent 10 }}
        {{- range $name, $value := .Values.comp.extraEnv }}
          - name: {{ $name }}
            value: {{ $value | quote }}
        {{- end }}
          envFrom:
          - secretRef:
              name: {{ include "persistence.fullname" . }}
          ports:
            - name: {{ include "common-appPortName" . }}
              containerPort: {{ .Values.comp.containerPort }}
              protocol: TCP
      volumes:
      {{- include "common-deployment-volumes" . | nindent 6}}
    {{- include "common-deployment-spec" . | nindent 6 }}
{{- end }}
