{{- $c := (dict "comp" .Values.persistence "context" $) -}}
{{- if $c.comp.enabled }}
{{- include "comp-common-manifests" $c }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "persistence.name" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/component: persistence
spec:
  {{- if kindIs "int64" $c.comp.replicaCount }}
  replicas: {{ $c.comp.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "vulcan.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: persistence
  template:
    metadata:
      labels: {{- include "vulcan.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: persistence
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/persistence/secrets.yaml") . | sha256sum }}
        {{- include "comp-common-annotations" $c | nindent 8 }}
        {{- with $c.comp.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- include "comp-common-spec" $c | nindent 6 }}
    {{- with $c.comp.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml $c.comp.podSecurityContext | nindent 8 }}
      initContainers:
        - name: waitfordb
          image: "{{ $c.comp.waitfordb.image.repository }}:{{ $c.comp.waitfordb.image.tag }}"
          imagePullPolicy: Always
          command: ['sh', '-c', 'until pg_isready -t 5; do echo WaitingDB; done;']
          env:
          - name: PGHOST
            value: "{{ $c.comp.db.host | default (include "postgresqlHost" .) }}"
          - name: PGPORT
            value: "{{ $c.comp.db.port }}"
      containers:
        {{- include "comp-common-containers" $c | nindent 8}}
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml $c.comp.securityContext | nindent 12 }}
          image: "{{ $c.comp.image.repository }}:{{ $c.comp.image.tag }}"
          imagePullPolicy: {{ $c.comp.image.pullPolicy }}
        {{- if $c.comp.conf.loadSQL }}
          command: ["/app/run.sh"]
          args: ["/conf/load.sql"]
        {{- end }}
          env:
          - name: PORT
            value: "{{ $c.comp.containerPort }}"
          - name: POSTGRES_DB
            value: "{{ $c.comp.db.name }}"
          - name: POSTGRES_HOST
            value: "{{ $c.comp.db.host | default (include "postgresqlHost" .) }}"
          - name: POSTGRES_PORT
            value: "{{ $c.comp.db.port }}"
          - name: POSTGRES_USER
            value: "{{ $c.comp.db.user }}"
          - name: POSTGRES_SSLMODE
            value: "{{ $c.comp.db.sslMode }}"
          {{- if $c.comp.db.ca }}
          - name: POSTGRES_CA_B64
            value: "{{ $c.comp.db.ca | b64enc }}"
          {{- end }}
          - name: LOG_LEVEL
            value: "{{ $c.comp.conf.logLevel }}"
          - name: STREAM_CHANNEL
            value: "{{ $c.comp.conf.channel }}"
          - name: REGION
            value: "{{ $c.comp.conf.region | default (include "region" .) }}"
          - name: SCANS_BUCKET
            value: "{{ $c.comp.conf.s3Scans }}"
          - name: SNS_TOPIC_ARN
            value: "{{ $c.comp.conf.snsTopic }}"
          - name: AWS_REGION
            value: "{{ $c.comp.conf.region | default (include "region" .) }}"
          - name: NESSUS_CHECK_QUEUE
            value: "{{ $c.comp.conf.nessusCheckQueue }}"
          - name: RAILS_MAX_THREADS
            value: "{{ $c.comp.conf.railsMaxThreads }}"
          - name: AWS_CREATE_CHECKS_SQS_URL
            value: "{{ $c.comp.conf.awsCreateChecksSqsUrl | default (printf "%s/%s" (include "sqsEndpoint" .) $c.comp.conf.awsCreateChecksSqsName) }}"
          - name: AWS_CREATE_CHECKS_WORKERS
            value: "{{ $c.comp.conf.awsCreateChecksWorkers }}"
        {{- include "comp-common-envs" $c | nindent 10 }}
        {{- range $name, $value := $c.comp.extraEnv }}
          - name: {{ $name }}
            value: {{ $value | quote }}
        {{- end }}
          envFrom:
          - secretRef:
              name: {{ include "persistence.name" . }}
          ports:
            - name: {{ include "comp-common-appPortName" $c }}
              containerPort: {{ $c.comp.containerPort }}
              protocol: TCP
      {{- if $c.comp.conf.loadSQL }}
          volumeMounts:
          - name: load
            mountPath: /conf
      {{- end }}
          {{- include "comp-common-lifecycle" $c | nindent 10 }}
          resources:
            {{- toYaml $c.comp.resources | nindent 12 }}
      volumes:
      {{- include "comp-common-volumes" $c | nindent 6}}
      {{- if $c.comp.conf.loadSQL }}
      - name: "load"
        configMap:
          name: {{ include "persistence.name" . }}-load
      {{- end }}
      {{- with $c.comp.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with $c.comp.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $c.comp.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
