{{- $c := (dict "comp" .Values.persistence "context" $) -}}
{{- if and $c.comp.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "persistence.name" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/component: persistence
type: Opaque
data:
  POSTGRES_PASSWORD: {{ $c.comp.db.password | b64enc | quote }}
  SECRET_KEY_BASE: {{ $c.comp.conf.secretKeyBase | b64enc | quote  }}
{{- end }}
