{{- $_ := (set .Values "comp" .Values.persistence) -}}
{{- if and .Values.comp.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "persistence.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.comp.db.password | b64enc | quote }}
  SECRET_KEY_BASE: {{ .Values.comp.conf.secretKeyBase | b64enc | quote  }}
{{- end }}
