{{ if .Values.defaultBackend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    name: {{ include "ui.fullname" . }}-db
  name: {{ include "ui.fullname" . }}-db
data:
  index.html: {{ (tpl .Values.defaultBackend.index . | quote ) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ui.fullname" . }}-db
  labels:
    {{- include "ui.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ui.name" . }}-db
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "ui.name" . }}-db
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: db
          image: nginx:alpine
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
        {{- range $name, $value := .Values.defaultBackend.extraEnv }}
          - name: {{ $name }}
            value: {{ $value | quote }}
        {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
          - name: load
            mountPath: /usr/share/nginx/html
      volumes:
      - name: load
        configMap:
          name: {{ include "ui.fullname" . }}-db
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ui.fullname" . }}-db
  labels:
    {{- include "ui.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "ui.name" . }}-db
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
