apiVersion: v2
name: vulcan
description: A Helm chart for deploying Vulcan
home: https://github.com/adevinta/vulcan-charts
icon: https://raw.githubusercontent.com/adevinta/vulcan-charts/master/docs/logo/vulcan.png

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 0.2.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 1.16.0

dependencies:
- name: api
  version: 0.2.0
  repository: "file://../api"
  condition: api.enabled
- name: crontinuous
  version: 0.2.0
  repository: "file://../crontinuous"
  condition: crontinuous.enabled
- name: insights
  version: 0.2.0
  repository: "file://../insights"
  condition: insights.enabled
- name: ui
  version: 0.2.0
  repository: "file://../ui"
  condition: ui.enabled
- name: metrics
  version: 0.2.0
  repository: "file://../metrics"
  condition: metrics.enabled
- name: reportsgenerator
  version: 0.2.0
  repository: "file://../reportsgenerator"
  condition: reportsgenerator.enabled
- name: vulndbapi
  version: 0.2.0
  repository: "file://../vulndbapi"
  condition: vulndbapi.enabled
- name: vulndb
  version: 0.2.0
  repository: "file://../vulndb"
  condition: vulndb.enabled
- name: postgresql
  version: 8.9.4
  repository: https://charts.bitnami.com/bitnami
  condition: global.postgresql.enabled
- name: goaws
  version: 0.2.0
  repository: "file://../goaws"
  condition: global.sns.enabled,global.sqs.enabled
- name: minio
  version: 3.3.6
  repository: https://charts.bitnami.com/bitnami
  alias: minio
  condition: global.minio.enabled
