# Default values for vulcan.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  domain: vulcan.local
  region: local-region
  minio:
    enabled: true
  sns:
    enabled: true
  sqs:
    enabled: true
  postgresql:
    enabled: true

postgresql:
  enabled: true
  postgresqlUsername: postgres
  postgresqlPassword: TBD
  postgresqlDatabase: persistence
  initdbScripts:
    initial-dbs.sql: |
      CREATE DATABASE api;
      CREATE DATABASE scanengine;
      CREATE DATABASE reportsgenerator;
  master:
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9187"
  resources:
    requests:
      cpu: "0"
      memory: "0"
  persistence:
    enabled: false
  metrics:
    enabled: true

goaws:
  containerPort: 80
  config:
    goaws.yaml: |
      Local:
        Host: {{ .Release.Name }}-goaws
        Port: {{ .Values.containerPort }}
        AccountId: "012345678900"
        LogToFile: false
        QueueAttributeDefaults:
          VisibilityTimeout: 30
          ReceiveMessageWaitTimeSeconds: 0
        Queues:
          - Name: VulcanK8SAPIScans
          - Name: VulcanK8SChecksGeneric
          - Name: VulcanK8SChecksTenable
          - Name: VulcanK8SMetricsChecks
          - Name: VulcanK8SMetricsScans
          - Name: VulcanK8SScanEngineChecks
          - Name: VulcanK8SReportsGenerator
        Topics:
          - Name: VulcanK8SChecks
            Subscriptions:
              - QueueName: VulcanK8SMetricsChecks
                Raw: true
              - QueueName: VulcanK8SScanEngineChecks
                Raw: true
                #FilterPolicy: '{"foo": ["bar"]}'
          - Name: VulcanK8SScans
            Subscriptions:
              - QueueName: VulcanK8SAPIScans
                Raw: true
              - QueueName: VulcanK8SMetricsScans
                Raw: true
          - Name: VulcanK8SReportsGen
            Subscriptions:
              - QueueName: VulcanK8SReportsGenerator
                Raw: true
        RandomLatency:
          Min: 0
          Max: 0

minio:
  mode: standalone
  defaultBuckets: "reports,logs,scans,insights,public-insights,crontinuous"
  serviceAccount:
    create: false
  persistence:
    enabled: false
  service:
    port: 80
    type: NodePort    # To bypass problem with minio.chart
  accessKey:
    password: AKIAIOSFODNN7EXAMPLE
  secretKey:
    password: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
  extraEnv:
    - name: MINIO_REGION_NAME
      value: local-region

defaults:
  db: &db
    user: postgres
    password: TBD
    sslMode: disable
  proxy:  &proxy
    proxy:
      enabled: true
      port: 9090  # We use non 80 port to prevent prometheus trying to access metrics on port 80
      probe: false
      probePath: /healthz
      probeInitialDelay: 5
      probeTimeoutSeconds: 3
      resources: {}

results:
  <<: *proxy
  conf:
    bucketReports: reports
    bucketLogs: logs

persistence:
  <<: *proxy
  db:
    <<: *db
    name: persistence
  conf:
    snsTopic: arn:aws:sns:local:012345678900:VulcanK8SChecks
    nessusCheckQueue: VulcanK8SChecksTenable
    s3Scans: scans

    loadSQL:
    queueGenId: e4febc2a-3c75-40a8-9dea-26d893050f75
    queueGenArn: arn:aws:sqs:local:012345678900:VulcanK8SChecksGeneric
    queueGenName: VulcanK8SChecksGeneric
    queueNesId: a4febc2a-3c75-40a8-9dea-26d893050f75
    queueNesArn: arn:aws:sqs:local:012345678900:VulcanK8SChecksTenable
    queueNesName: VulcanK8SChecksTenable

stream:
  <<: *proxy
  db:
    <<: *db
    name: persistence

api:
  <<: *proxy
  db:
    <<: *db
    name: api
  conf:
    bucketReports: reports
    bucketLogs: logs
    s3PrivateBucket: insights
    s3PublicBucket: public-insights
    queueArn: arn:aws:sqs:local:012345678900:VulcanK8SAPIScans
    queueName: VulcanK8SAPIScans
  ingress:
    path: /api

crontinuous:
  <<: *proxy
  conf:
    crontinuousBucket: crontinuous

scanengine:
  <<: *proxy
  conf:
    logLevel: "error"
    queueArn: arn:aws:sqs:local:012345678900:VulcanK8SScanEngineChecks
    queueName: VulcanK8SScanEngineChecks
    snsArn: arn:aws:sns:local:012345678900:VulcanK8SScans
  db:
    <<: *db
    name: scanengine

ui:
  <<: *proxy

insights:
  <<: *proxy
  conf:
    proxies:
      - name: private
        s3Bucket: insights
        prefix: ""
      - name: public
        s3Bucket: public-insights
        prefix: "/public"

reportsgenerator:
  <<: *proxy
  conf:
    logLevel: "error"
    queueArn: arn:aws:sqs:local:012345678900:VulcanK8SReportsGenerator
    queueName: VulcanK8SReportsGenerator
    generators:
      scan:
        publicBucket: public-insights
        privateBucket: insights
  db:
    <<: *db
    name: reportsgenerator

metrics:
  conf:
    checksQueueArn: arn:aws:sqs:local:012345678900:VulcanK8SMetricsChecks
    checksQueueName: VulcanK8SMetricsChecks
    scansQueueArn: arn:aws:sqs:local:012345678900:VulcanK8SMetricsScans
    scansQueueName: VulcanK8SMetricsScans

sqsExporter:
  enabled: true
  image:
    repository: jesusfcr/sqs-exporter
    tag: custom-endpoint
  queueNamePrefix: VulcanK8S
  resources: {}

agent:
  enabled: true
  image:
    repository: adevinta/vulcan-agent
    tag: latest
    pullPolicy: Always
  containerPort: 80
  conf:
    jobQueueId: 00000000-0000-0000-0000-000000000000
    logLevel: debug
    concurrentJobs: 1000
    # persistenceEndpint: http://vulcan-persistence/v1
    # resultsEndpoint: http://vulcan-results/v1
    # streamEndpoint: ws://vulcan-stream/stream
    checkLogLevel: debug
    nessusEndpoint: https://cloud.tenable.com
    nessusUsername: SECRET
    nessusPassword: SECRET
    githubEnterpriseToken: SECRET
    gatewayEndpoint: http://gateway:8080/async-function
  service:
    enabled: true
    type: ClusterIP
    port: 80

openfaas:
  enabled: false
  functionNamespace:          # Required ... the same namespace
  ingress:
    enabled: true
  nats:
    enableMonitoring: true
  ingressOperator:
    create: false
  faasIdler:
    dryRun: false
  clusterRole: false
  imagePullPolicy: Always
  serviceType: NodePort
  gateway:
    directFunctions: true
    replicas: 1
    readTimeout : "30s"
    writeTimeout : "3700s"
    upstreamTimeout : "3600s"  # Must be smaller than read/write_timeout
  openfaasImagePullPolicy: IfNotPresent
  generateBasicAuth: true
  basic_auth: true
  queueWorker:
    maxInflight: 100

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
