apiVersion: v1
kind: Secret
metadata:
  labels:
    name: {{ include "crontinuous.fullname" . }}
  name: {{ include "crontinuous.fullname" . }}
type: Opaque
data:
  VULCAN_TOKEN: {{ .Values.conf.vulcanToken | b64enc | quote }}
