{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "crontinuous.serviceAccountName" . }}
  labels:
{{ include "crontinuous.labels" . | nindent 4 }}
{{- end -}}
