apiVersion: v1
kind: Secret
metadata:
  labels:
    name: {{ include "agent.fullname" . }}
  name: {{ include "agent.fullname" . }}
type: Opaque
data:
  NESSUS_PASSWORD: {{ .Values.conf.nessusPassword | b64enc | quote }}
  NESSUS_USERNAME: {{ .Values.conf.nessusUsername | b64enc | quote }}
  GITHUB_ENTERPRISE_TOKEN: {{ .Values.conf.githubEnterpriseToken | b64enc | quote }}
