{{- $_ := (set .Values "comp" .Values.vulndbapi) -}}
{{- if and .Values.comp.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vulndbapi.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/name: vulndbapi
type: Opaque
data:
  PG_PASSWORD: {{ .Values.comp.db.password | b64enc | quote }}
{{- end }}
