{{- $c := (dict "comp" .Values.redis "context" $) -}}
{{- if $c.comp.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/name: redis
spec:
  {{- if kindIs "int64" $c.comp.replicaCount }}
  replicas: {{ $c.comp.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "vulcan.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: redis
  template:
    metadata:
      labels: {{- include "vulcan.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/name: redis
      annotations:
        {{- with $c.comp.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- with $c.comp.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $c.comp.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - name: {{ $c.comp.name }}
          {{- with $c.comp.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        image: "{{ $c.comp.image.repository }}:{{ $c.comp.image.tag }}"
        imagePullPolicy: {{ $c.comp.image.pullPolicy }}
        args: ["--requirepass", "$(REDIS_PASSWORD)"]
        envFrom:
          - secretRef:
              name: {{ include "redis.fullname" . }}
        {{- range $name, $value := $c.comp.extraEnv }}
        - name: {{ $name }}
          value: {{ $value | quote }}
        {{- end }}
        ports:
          - name: {{ include "comp-common-appPortName" $c }}
            containerPort: {{ $c.comp.containerPort }}
            protocol: TCP
          {{- with $c.comp.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
      {{- with $c.comp.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with $c.comp.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $c.comp.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
