{{- $_ := (set .Values "comp" .Values.redis) -}}
{{- if and .Values.comp.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/name: redis
type: Opaque
data:
  REDIS_PASSWORD: {{ .Values.comp.conf.redisPassword | b64enc | quote }}
{{- end }}
