{{- $_ := (set .Values "comp" .Values.scanengine) -}}
{{- if .Values.comp.enabled }}
{{- include "common-manifests" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scanengine.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.comp.name }}
spec:
  {{- if kindIs "int64" .Values.comp.replicaCount }}
  replicas: {{ .Values.comp.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "vulcan.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: {{ .Values.comp.name }}
  template:
    metadata:
      labels: {{- include "vulcan.podLabels" . | nindent 8 }}
        app.kubernetes.io/name: {{ .Values.comp.name }}
      annotations:
        checksum/secrets: {{ include "scanengine-secrets" . | sha256sum }}
        {{- include "common-annotations" . | nindent 8 }}
    spec:
      initContainers:
        {{- include "common-deployment-init-waitfordb" . | nindent 8 }}
      containers:
        {{- include "common-deployment-sidecars" . | nindent 8 }}
        - name: {{ .Values.comp.name }}
          {{- include "common-container" . | nindent 10 }}
          env:
          - name: PORT
            value: {{ .Values.comp.containerPort | quote }}
          - name: PG_HOST
            value: {{ include "pg.host" . | quote }}
          - name: PG_NAME
            value: {{ include "pg.database" . | quote }}
          - name: PG_USER
            value: {{ include "pg.username" . | quote }}
          - name: PG_PORT
            value: {{ include "pg.port" . | quote }}
          - name: PG_SSLMODE
            value: {{ include "pg.sslMode" . | quote }}
          - name: PG_CA_B64
            value: {{ include "pg.b64ca" . | quote }}
          - name: LOG_LEVEL
            value: {{ .Values.comp.conf.logLevel | quote }}
          - name: PERSISTENCE_HOST
            value: {{ .Values.comp.conf.persistenceHost | default  (include "persistence.fullname" .) | quote }}
          - name: CHECKS_SQS_ARN
            value: {{ tpl .Values.comp.conf.queueArn . | quote }}
          - name: SCANS_SNS_ARN
            value: {{ tpl .Values.comp.conf.scansSNS.topicArn . | quote }}
          - name: CHECKS_SNS_ARN
            value: {{ tpl .Values.comp.conf.checksSNS.topicArn . | quote }}
          - name: STREAM_URL
            value: {{ .Values.comp.conf.streamUrl | default  (include "stream.url" .) | quote }}
          - name: CHECKS_CREATOR_WORKERS
            value: {{ .Values.comp.conf.checkCreator.numOfWorkers | quote }}
          - name: CHECKS_CREATOR_PERIOD
            value: {{ .Values.comp.conf.checkCreator.period | quote }}
          - name: QUEUES_DEFAULT_ARN
            value: {{ tpl .Values.comp.conf.queues.default.arn .| quote }}
          {{- range $index, $value := .Values.comp.conf.queues.other }}
          - name: "QUEUES_{{ add1 $index }}_ARN"
            value: {{ tpl $value.arn $ | quote }}
          - name: "QUEUES_{{ add1 $index }}_CHECKTYPES"
            value: {{ $value.checktypes | quote }}
          {{- end }}
        {{- include "common-container-envs" . | nindent 10 }}
          envFrom:
          - secretRef:
              name: {{ include "scanengine.fullname" . }}
          ports:
            - name: {{ include "common-appPortName" . }}
              containerPort: {{ .Values.comp.containerPort }}
              protocol: TCP
          volumeMounts:
          {{- include "common-deployment-volumeMounts" . | nindent 12 }}
      volumes:
      {{- include "common-deployment-volumes" . | nindent 6 }}
    {{- include "common-deployment-spec" . | nindent 6 }}
{{- end }}
