{{- $_ := (set .Values "comp" .Values.scanengine) -}}
{{- if .Values.comp.enabled }}
{{- include "common-manifests" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scanengine.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/name: scanengine
spec:
  {{- if kindIs "int64" .Values.comp.replicaCount }}
  replicas: {{ .Values.comp.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "vulcan.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: scanengine
  template:
    metadata:
      labels: {{- include "vulcan.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/name: scanengine
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/scanengine/secrets.yaml") . | sha256sum }}
        {{- include "common-annotations" . | nindent 8 }}
        {{- with .Values.comp.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      initContainers:
        {{- include "common-deployment-init-waitfordb" . | nindent 8 }}
      containers:
        {{- include "common-deployment-sidecars" . | nindent 8 }}
        - name: {{ .Values.comp.name }}
          {{- include "common-container" . | nindent 10 }}
          env:
          - name: PORT
            value: {{ .Values.comp.containerPort | quote }}
          - name: PG_HOST
            value: {{ .Values.comp.db.host | default (include "postgresqlHost" .) | quote }}
          - name: PG_NAME
            value: {{ .Values.comp.db.name | quote }}
          - name: PG_USER
            value: {{ .Values.comp.db.user | quote }}
          - name: PG_PORT
            value: {{ .Values.comp.db.port | quote }}
          - name: PG_SSLMODE
            value: {{ .Values.comp.db.sslMode | quote }}
          {{- if .Values.comp.db.ca }}
          - name: PG_CA_B64
            value: {{ .Values.comp.db.ca | b64enc | quote }}
          {{- end }}
          - name: LOG_LEVEL
            value: {{ .Values.comp.conf.logLevel | quote }}
          - name: PERSISTENCE_HOST
            value: {{ .Values.comp.conf.persistenceHost | default  (include "persistence.fullname" .) | quote }}
          - name: CHECKS_SQS_ARN
            value: {{ .Values.comp.conf.queueArn | quote }}
          - name: "SCANS_SNS_ARN"
            value: {{ .Values.comp.conf.scansSNS.topicArn | quote }}
          - name: "CHECKS_SNS_ARN"
            value: {{ .Values.comp.conf.checksSNS.topicArn | quote }}
          - name: "STREAM_URL"
            value: {{ .Values.comp.conf.streamUrl | default  (include "stream.url" .) | quote }}
          - name: "CHECKS_CREATOR_WORKERS"
            value: {{ .Values.comp.conf.checkCreator.numOfWorkers | quote }}
          - name: "CHECKS_CREATOR_PERIOD"
            value: {{ .Values.comp.conf.checkCreator.period | quote }}
          - name: "QUEUES_DEFAULT_ARN"
            value: {{ .Values.comp.conf.queues.default.arn | quote }}
          - name: "QUEUES_NESSUS_ARN"
            value: {{ .Values.comp.conf.queues.nessus.arn | quote }}
          - name: "QUEUES_NESSUS_CHECKTYPES"
            value: {{ .Values.comp.conf.queues.nessus.checktypes | quote }}
        {{- include "common-container-envs" . | nindent 10 }}
        {{- range $name, $value := .Values.comp.extraEnv }}
          - name: {{ $name }}
            value: {{ $value | quote }}
        {{- end }}
          envFrom:
          - secretRef:
              name: {{ include "scanengine.fullname" . }}
          ports:
            - name: {{ include "common-appPortName" . }}
              containerPort: {{ .Values.comp.containerPort }}
              protocol: TCP
      volumes:
      {{- include "common-deployment-volumes" . | nindent 6}}
    {{- include "common-deployment-spec" . | nindent 6 }}
{{- end }}
