{{- $c := (dict "comp" .Values.scanengine "context" $) -}}
{{- if $c.comp.enabled }}
{{- include "comp-common-manifests" $c }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scanengine.name" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/component: scanengine
spec:
  {{- if kindIs "int64" $c.comp.replicaCount }}
  replicas: {{ $c.comp.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "vulcan.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: scanengine
  template:
    metadata:
      labels: {{- include "vulcan.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: scanengine
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/scanengine/secrets.yaml") . | sha256sum }}
        {{- include "comp-common-annotations" $c | nindent 8 }}
        {{- with $c.comp.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- include "comp-common-spec" $c | nindent 6 }}
    {{- with $c.comp.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml $c.comp.podSecurityContext | nindent 8 }}
      initContainers:
        - name: waitfordb
          image: "{{ $c.comp.waitfordb.image.repository }}:{{ $c.comp.waitfordb.image.tag }}"
          imagePullPolicy: Always
          command: ['sh', '-c', 'until pg_isready -t 5; do echo WaitingDB; done;']
          env:
          - name: PGHOST
            value: "{{ $c.comp.db.host | default (include "postgresqlHost" .) }}"
          - name: PGPORT
            value: "{{ $c.comp.db.port }}"
      containers:
        {{- include "comp-common-containers" $c | nindent 8}}
        - name: {{ $c.comp.name }}
          securityContext:
            {{- toYaml $c.comp.securityContext | nindent 12 }}
          image: "{{ $c.comp.image.repository }}:{{ $c.comp.image.tag }}"
          imagePullPolicy: {{ $c.comp.image.pullPolicy }}
          env:
          - name: PORT
            value: "{{ $c.comp.containerPort }}"
          - name: PG_HOST
            value: "{{ $c.comp.db.host | default (include "postgresqlHost" .) }}"
          - name: PG_NAME
            value: "{{ $c.comp.db.name }}"
          - name: PG_USER
            value: "{{ $c.comp.db.user }}"
          - name: PG_PORT
            value: "{{ $c.comp.db.port }}"
          - name: PG_SSLMODE
            value: "{{ $c.comp.db.sslMode }}"
          {{- if $c.comp.db.ca }}
          - name: PG_CA_B64
            value: "{{ $c.comp.db.ca | b64enc }}"
          {{- end }}
          - name: LOG_LEVEL
            value: "{{ $c.comp.conf.logLevel }}"
          - name: PERSISTENCE_HOST
            value: "{{ $c.comp.conf.persistenceHost | default  (include "persistenceHost" .) }}"
          - name: CHECKS_SQS_ARN
            value: "{{ $c.comp.conf.queueArn }}"
          - name: "SCANS_SNS_ARN"
            value: "{{ $c.comp.conf.scansSNS.topicArn }}"
          - name: "CHECKS_SNS_ARN"
            value: "{{ $c.comp.conf.checksSNS.topicArn }}"
          - name: "STREAM_URL"
            value: "{{ $c.comp.conf.streamUrl | default  (include "streamUrl" .) }}"
          - name: "CHECKS_CREATOR_WORKERS"
            value: "{{ $c.comp.conf.checkCreator.numOfWorkers }}"
          - name: "CHECKS_CREATOR_PERIOD"
            value: "{{ $c.comp.conf.checkCreator.period }}"
          - name: "QUEUES_DEFAULT_ARN"
            value: "{{ $c.comp.conf.queues.default.arn }}"
          - name: "QUEUES_NESSUS_ARN"
            value: "{{ $c.comp.conf.queues.nessus.arn }}"
          - name: "QUEUES_NESSUS_CHECKTYPES"
            value: {{ $c.comp.conf.queues.nessus.checktypes | quote }}
        {{- include "comp-common-envs" $c | nindent 10 }}
        {{- range $name, $value := $c.comp.extraEnv }}
          - name: {{ $name }}
            value: {{ $value | quote }}
        {{- end }}
          envFrom:
          - secretRef:
              name: {{ include "scanengine.name" . }}
          ports:
            - name: {{ include "comp-common-appPortName" $c }}
              containerPort: {{ $c.comp.containerPort }}
              protocol: TCP
          {{- include "comp-common-lifecycle" $c | nindent 10 }}
          resources:
            {{- toYaml $c.comp.resources | nindent 12 }}
      volumes:
      {{- include "comp-common-volumes" $c | nindent 6}}
      {{- if $c.comp.conf.loadSQL }}
      - name: "load"
        configMap:
          name: {{ include "scanengine.name" . }}-load
      {{- end }}
      {{- with $c.comp.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with $c.comp.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $c.comp.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
