{{- $_ := (set .Values "comp" .Values.scanengine) -}}
{{- if and .Values.comp.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scanengine.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/name: scanengine
type: Opaque
data:
  PG_PASSWORD: {{ .Values.comp.db.password | b64enc | quote }}
{{- end }}
