{{- $_ := (set .Values "comp" .Values.stream) -}}
{{- if .Values.comp.enabled }}
{{- include "common-manifests" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "comp.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Values.comp.name }}
spec:
  {{- if kindIs "int64" .Values.comp.replicaCount }}
  replicas: {{ .Values.comp.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "vulcan.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: {{ .Values.comp.name }}
  template:
    metadata:
      labels: {{- include "vulcan.podLabels" . | nindent 8 }}
        app.kubernetes.io/name: {{ .Values.comp.name }}
      annotations:
        {{- if (include "vulcan.redis.password" .) }}
        checksum/secrets: {{ include "stream-secrets" . | sha256sum }}
        {{- end }}
        {{- include "common-annotations" . | nindent 8 }}
    spec:
      {{- if .Values.comp.initContainers }}
      initContainers:
        {{ tpl (toYaml .Values.comp.initContainers) . | nindent 8 }}
      {{- end }}
      containers:
        {{- include "common-deployment-sidecars" . | nindent 8 }}
        - name: {{ .Values.comp.name }}
          {{- include "common-container" . | nindent 10 }}
          env:
          - name: PORT
            value: {{ .Values.comp.containerPort | quote }}
          - name: LOG_LEVEL
            value: {{ .Values.comp.conf.logLevel | quote }}
          - name: REDIS_HOST
            value: {{ include "vulcan.redis.host" . | quote }}
          - name: REDIS_USR
            value: {{ include "vulcan.redis.username" . | quote }}
          - name: REDIS_PORT
            value: {{ include "vulcan.redis.port" . | quote }}
          - name: REDIS_DB
            value: {{ include "vulcan.redis.db" . | quote }}
          - name: REDIS_TTL
            value: {{ .Values.comp.conf.ttl | quote }}
        {{- if or (include "vulcan.redis.password" .) .Values.comp.redis.existingSecret }}
          - name: REDIS_PWD
            valueFrom:
              secretKeyRef:
                name: {{ coalesce (tpl .Values.comp.redis.existingSecret .) (include "comp.fullname" .) }}
                key: {{ .Values.comp.redis.existingSecretPasswordKey | default "REDIS_PWD" }}
        {{- end }}
        {{- include "common-container-envs" . | nindent 10 }}
          ports:
            - name: {{ include "common-appPortName" . }}
              containerPort: {{ .Values.comp.containerPort }}
              protocol: TCP
          volumeMounts:
          {{- include "common-deployment-volumeMounts" . | nindent 12 }}
      volumes:
      {{- include "common-deployment-volumes" . | nindent 6 }}
    {{- include "common-deployment-spec" . | nindent 6 }}
{{- end }}
