{{- $_ := (set .Values "comp" .Values.stream) -}}
{{- if .Values.comp.enabled }}
{{- include "common-manifests" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stream.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/name: stream
spec:
  {{- if kindIs "int64" .Values.comp.replicaCount }}
  replicas: {{ .Values.comp.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "vulcan.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: stream
  template:
    metadata:
      labels: {{- include "vulcan.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/name: stream
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/stream/secrets.yaml") . | sha256sum }}
        {{- include "common-annotations" . | nindent 8 }}
        {{- with .Values.comp.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- include "common-spec" . | nindent 6 }}
    {{- with .Values.comp.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.comp.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        {{- include "common-containers" . | nindent 8}}
        - name: {{ .Values.comp.name }}
          {{- with .Values.comp.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.comp.image.repository }}:{{ .Values.comp.image.tag }}"
          imagePullPolicy: {{ .Values.comp.image.pullPolicy }}
          env:
          - name: PORT
            value: {{ .Values.comp.containerPort | quote }}
          - name: LOG_LEVEL
            value: {{ .Values.comp.conf.logLevel | quote }}
          - name: REDIS_HOST
            value: {{ .Values.comp.conf.redis.host | quote }}
          - name: REDIS_PORT
            value: {{ .Values.comp.conf.redis.port | quote }}
          - name: REDIS_USR
            value: {{ .Values.comp.conf.redis.usr | quote }}
          - name: REDIS_DB
            value: {{ .Values.comp.conf.redis.db | quote }}
          - name: REDIS_TTL
            value: {{ .Values.comp.conf.redis.ttl | quote }}
        {{- include "common-envs" . | nindent 10 }}
        {{- range $name, $value := .Values.comp.extraEnv }}
          - name: {{ $name }}
            value: {{ $value | quote }}
        {{- end }}
          envFrom:
          - secretRef:
              name: {{ include "stream.fullname" . }}
          ports:
            - name: {{ include "common-appPortName" . }}
              containerPort: {{ .Values.comp.containerPort }}
              protocol: TCP
          {{- include "common-lifecycle" . | nindent 10 }}
          {{- with .Values.comp.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
      {{- include "common-volumes" . | nindent 6}}
      {{- with .Values.comp.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.comp.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.comp.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
