{{- $c := (dict "comp" .Values.stream "context" $) -}}
{{- if and $c.comp.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stream.name" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/component: stream
type: Opaque
data:
  REDIS_PWD: {{ $c.comp.conf.redis.pwd | b64enc | quote }}
{{- end }}
