{{- $_ := (set .Values "comp" .Values.stream) -}}
{{- if and .Values.comp.enabled (include "redis.password" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stream.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/name: stream
type: Opaque
data:
  REDIS_PWD: {{ include "redis.encryptedPassword" . | quote }}
{{- end }}
