{{- $_ := (set .Values "comp" .Values.stream) -}}
{{- if and .Values.comp.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stream.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/name: stream
type: Opaque
data:
  REDIS_PWD: {{ .Values.comp.conf.redis.pwd | b64enc | quote }}
{{- end }}
