{{- $_ := (set .Values "comp" .Values.reportsgenerator) -}}
{{- if and .Values.comp.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reportsgenerator.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/name: reportsgenerator
type: Opaque
data:
  PG_PASSWORD: {{ include "pg.encryptedPassword" . | quote }}
{{- end }}
