{{- $c := (dict "comp" .Values.reportsgenerator "context" $) -}}
{{- if and $c.comp.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reportsgenerator.name" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/component: reportsgenerator
type: Opaque
data:
  PG_PASSWORD: {{ $c.comp.db.password | b64enc | quote }}
{{- end }}
