{{- $c := (dict "comp" .Values.goaws "context" $) -}}
{{- if and $c.comp.enabled $c.comp.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "goaws.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/name: goaws
data:
{{ tpl ( toYaml $c.comp.config ) . | indent 2 }}
{{- end }}
