minio:
  enabled: true
  ingress:
    enabled: true
    hostname: minio.vulcan.local

goaws:
  enabled: true
  ingress:
    enabled: true
    hosts:
      - host: goaws.vulcan.local
        paths: [/]

postgresql:
  enabled: true

redis:
  enabled: true

results:
  conf:
    linkBase: https://results.vulcan.local
  ingress:
    enabled: true
    hosts:
      - host: results.vulcan.local
        paths: [/]

stream:
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    enabled: true
    hosts:
      - host: stream.vulcan.local
        paths: [/]

persistence:
  ingress:
    enabled: true
    hosts:
      - host: persistence.vulcan.local
        paths: [/]

api:
  conf:
    saml:
      callback: https://www.vulcan.local/api/v1/login/callback
      trustedDomains: '["www.vulcan.local"]'
    globalPolicies:
      - name: web-scanning-global
        allowedAssettypes:
        blockedAssettypes:
        allowedChecks:
          - vulcan-zap
        blockedChecks:
        excludingSuffixes:
          - experimental
    vulcantrackerTeams: "team1,team2"
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-origin: "https://www.vulcan.local"
      nginx.ingress.kubernetes.io/proxy-body-size: 8m
    hosts:
      - host: www.vulcan.local
        paths: [/api]

crontinuous:
  conf:
    teamsWhitelistScan: '["team1", "team2"]'
    teamsWhitelistReport: '["team3"]'
  ingress:
    enabled: false

scanengine:
  ingress:
    enabled: false

ui:
  conf:
    apiUrl: https://www.vulcan.local/api/v1/
  ingress:
    enabled: true
    hosts:
      - host: www.vulcan.local
        paths: [/]

reportsgenerator:
  ingress:
    enabled: false

vulndbapi:
  ingress:
    enabled: true
    hosts:
      - host: vulndbapi.vulcan.local
        paths: [/]
  conf:
    readReplicaHost:

tracker:
  ingress:
    enabled: true
    hosts:
      - host: tracker.vulcan.local
        paths: [/]
  conf:
    logLevel: "error"
    awsServerCredentialKey: "/path/to/credentials/"
