{{- $c := (dict "comp" .Values.api "context" $) -}}
{{- if $c.comp.enabled }}
{{- include "comp-common-manifests" $c }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  {{- if kindIs "int64" $c.comp.replicaCount }}
  replicas: {{ $c.comp.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "vulcan.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels: {{- include "vulcan.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/api/secrets.yaml") . | sha256sum }}
        {{- include "comp-common-annotations" $c | nindent 8 }}
        {{- with $c.comp.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- include "comp-common-spec" $c | nindent 6 }}
    {{- with $c.comp.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml $c.comp.podSecurityContext | nindent 8 }}
      initContainers:
        - name: waitfordb
          image: "{{ $c.comp.waitfordb.image.repository }}:{{ $c.comp.waitfordb.image.tag }}"
          imagePullPolicy: Always
          command: ['sh', '-c', 'until pg_isready -t 5; do echo WaitingDB; done;']
          env:
          - name: PGHOST
            value: "{{ $c.comp.db.host | default (include "postgresqlHost" .) }}"
          - name: PGPORT
            value: "{{ $c.comp.db.port }}"
      containers:
        {{- include "comp-common-containers" $c | nindent 8}}
        - name: {{ $c.comp.name }}
          securityContext:
            {{- toYaml $c.comp.securityContext | nindent 12 }}
          image: "{{ $c.comp.image.repository }}:{{ $c.comp.image.tag }}"
          imagePullPolicy: {{ $c.comp.image.pullPolicy }}
          env:
          - name: PORT
            value: "{{ $c.comp.containerPort }}"
          - name: PG_HOST
            value: "{{ $c.comp.db.host | default (include "postgresqlHost" .) }}"
          - name: PG_NAME
            value: "{{ $c.comp.db.name }}"
          - name: PG_USER
            value: "{{ $c.comp.db.user }}"
          - name: PG_PORT
            value: "{{ $c.comp.db.port }}"
          - name: PG_SSLMODE
            value: "{{ $c.comp.db.sslMode }}"
          {{- if $c.comp.db.ca }}
          - name: PG_CA_B64
            value: "{{ $c.comp.db.ca | b64enc }}"
          {{- end }}
          - name: LOG_LEVEL
            value: "{{ $c.comp.conf.logLevel }}"
          - name: COOKIE_DOMAIN
            value: "{{ $c.comp.conf.cookieDomain | default (include "domain" .) }}"
          - name: SAML_MEATADATA
            value: "{{ $c.comp.conf.saml.metadata }}"
          - name: SAML_ISSUER
            value: "{{ $c.comp.conf.saml.issuer }}"
          - name: SAML_CALLBACK
            value: "{{ $c.comp.conf.saml.callback }}"
          - name: SAML_TRUSTED_DOMAINS
            value: {{ $c.comp.conf.saml.trustedDomains | quote }}
          - name: DEFAULT_OWNERS
            value: {{ $c.comp.conf.defaultOwners | quote }}
          - name: SCANENGINE_URL
            value: "{{ $c.comp.conf.scanengineUrl | default ( printf "%s/v1/" (include "scanengineUrl" .) ) }}"
          - name: SCHEDULER_URL
            value: "{{ $c.comp.conf.schedulerUrl | default (include "crontinuousUrl" .) }}"
          - name: SQS_QUEUE_ARN
            value: "{{ $c.comp.conf.queueArn }}"
          - name: REPORTS_SNS_ARN
            value: "{{ $c.comp.conf.reports.snsArn }}"
          - name: REPORTS_API_URL
            value: "{{ $c.comp.conf.reports.apiUrl | default (include "reportsgeneratorUrl" .) }}"
          - name: SCAN_REDIRECT_URL
            value: "{{ $c.comp.conf.reports.redirectUrl }}"
          - name: VULCAN_UI_URL
            value: "{{ $c.comp.conf.reports.vulcanUIUrl }}"
          - name: PERSISTENCE_HOST
            value: "{{ $c.comp.conf.persistenceHost | default  (include "persistence.fullname" .) }}"
          - name: VULNERABILITYDB_URL
            value: "{{ $c.comp.conf.vulndbapiUrl | default  (include "vulndbapiUrl" .) }}"
          - name: AWSCATALOGUE_KIND
            value: "{{ $c.comp.conf.awscatalogue.kind }}"
          - name: AWSCATALOGUE_URL
            value: "{{ $c.comp.conf.awscatalogue.url }}"
          - name: AWSCATALOGUE_RETRIES
            value: "{{ $c.comp.conf.awscatalogue.retries }}"
          - name: AWSCATALOGUE_RETRY_INTERVAL
            value: "{{ $c.comp.conf.awscatalogue.retry_interval}}"
        {{- include "comp-common-envs" $c | nindent 10 }}
        {{- range $name, $value := $c.comp.extraEnv }}
          - name: {{ $name }}
            value: {{ $value | quote }}
        {{- end }}
          envFrom:
          - secretRef:
              name: {{ include "api.fullname" . }}
          ports:
            - name: {{ include "comp-common-appPortName" $c }}
              containerPort: {{ $c.comp.containerPort }}
              protocol: TCP
          {{- include "comp-common-lifecycle" $c | nindent 10 }}
          resources:
            {{- toYaml $c.comp.resources | nindent 12 }}
      volumes:
      {{- include "comp-common-volumes" $c | nindent 6}}
      {{- with $c.comp.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with $c.comp.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $c.comp.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
