{{- $_ := set .Values "comp" .Values.api -}}
{{- if .Values.comp.enabled }}
{{- include "common-manifests" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
spec:
  {{- if kindIs "int64" .Values.comp.replicaCount }}
  replicas: {{ .Values.comp.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "vulcan.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "vulcan.podLabels" . | nindent 8 }}
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/api/secrets.yaml") . | sha256sum }}
        {{- include "common-annotations" . | nindent 8 }}
        {{- with .Values.comp.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      initContainers:
        {{- include "common-deployment-init-waitfordb" . | nindent 8 }}
      containers:
        {{- include "common-deployment-sidecars" . | nindent 8 }}
        - name: {{ .Values.comp.name }}
          {{- include "common-container" . | nindent 10 }}
          env:
          - name: PORT
            value: {{ .Values.comp.containerPort | quote }}
          - name: PG_HOST
            value: {{ include "pg.host" . | quote }}
          - name: PG_NAME
            value: {{ include "pg.database" . | quote }}
          - name: PG_USER
            value: {{ include "pg.username" . | quote }}
          - name: PG_PORT
            value: {{ include "pg.port" . | quote }}
          - name: PG_SSLMODE
            value: {{ include "pg.sslMode" . | quote }}
          - name: PG_CA_B64
            value: {{ include "pg.b64ca" . | quote }}
          - name: LOG_LEVEL
            value: {{ .Values.comp.conf.logLevel | quote }}
          - name: COOKIE_DOMAIN
            value: {{ .Values.comp.conf.cookieDomain | default (include "domain" .) | quote }}
          - name: SAML_MEATADATA
            value: {{ .Values.comp.conf.saml.metadata | quote }}
          - name: SAML_ISSUER
            value: {{ .Values.comp.conf.saml.issuer | quote }}
          - name: SAML_CALLBACK
            value: {{ .Values.comp.conf.saml.callback | quote }}
          - name: SAML_TRUSTED_DOMAINS
            value: {{ .Values.comp.conf.saml.trustedDomains | quote }}
          - name: DEFAULT_OWNERS
            value: {{ .Values.comp.conf.defaultOwners | quote }}
          - name: SCANENGINE_URL
            value: {{ .Values.comp.conf.scanengineUrl | default ( printf "%s/v1/" (include "scanengine.url" .) ) | quote }}
          - name: SCHEDULER_URL
            value: {{ .Values.comp.conf.schedulerUrl | default (include "crontinuous.url" .) | quote }}
          - name: SQS_QUEUE_ARN
            value: {{ .Values.comp.conf.queueArn | quote }}
          - name: REPORTS_SNS_ARN
            value: {{ .Values.comp.conf.reports.snsArn | quote }}
          - name: REPORTS_API_URL
            value: {{ .Values.comp.conf.reports.apiUrl | default (include "reportsgenerator.url" .) | quote }}
          - name: SCAN_REDIRECT_URL
            value: {{ .Values.comp.conf.reports.redirectUrl | quote }}
          - name: VULCAN_UI_URL
            value: {{ .Values.comp.conf.reports.vulcanUIUrl | quote }}
          - name: PERSISTENCE_HOST
            value: {{ .Values.comp.conf.persistenceHost | default  (include "persistence.fullname" .) | quote }}
          - name: VULNERABILITYDB_URL
            value: {{ .Values.comp.conf.vulndbapiUrl | default  (include "vulndbapi.url" .) | quote }}
          - name: AWSCATALOGUE_KIND
            value: {{ .Values.comp.conf.awscatalogue.kind | quote }}
          - name: AWSCATALOGUE_URL
            value: {{ .Values.comp.conf.awscatalogue.url | quote }}
          - name: AWSCATALOGUE_RETRIES
            value: {{ .Values.comp.conf.awscatalogue.retries | quote }}
          - name: AWSCATALOGUE_RETRY_INTERVAL
            value: {{ .Values.comp.conf.awscatalogue.retry_interval| quote }}
        {{- include "common-container-envs" . | nindent 10 }}
          envFrom:
          - secretRef:
              name: {{ include "api.fullname" . }}
          ports:
            - name: {{ include "common-appPortName" . }}
              containerPort: {{ .Values.comp.containerPort }}
              protocol: TCP
      volumes:
      {{- include "common-deployment-volumes" . | nindent 6 }}
    {{- include "common-deployment-spec" . | nindent 6 }}
{{- end }}
