{{- $_ := set .Values "comp" .Values.api -}}
{{- if and .Values.comp.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/name: api
type: Opaque
data:
  PG_PASSWORD: {{ .Values.comp.db.password | b64enc | quote }}
  SECRET_KEY: {{ .Values.comp.conf.secretKey | b64enc | quote }}
  AWSCATALOGUE_KEY: {{ .Values.comp.conf.awscatalogue.key | b64enc | quote }}
{{- end }}
