{{- $c := (dict "comp" .Values.api "context" $) -}}
{{- if and $c.comp.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.name" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
type: Opaque
data:
  PG_PASSWORD: {{ $c.comp.db.password | b64enc | quote }}
  SECRET_KEY: {{ $c.comp.conf.secretKey | b64enc | quote }}
  AWSCATALOGUE_KEY: {{ $c.comp.conf.awscatalogue.key | b64enc | quote }}
{{- end }}
