apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    name: {{ include "metrics.fullname" . }}
  name: {{ include "metrics.fullname" . }}
data:
  LOG_LEVEL: "{{ .Values.conf.logLevel }}"
  SQS_POLLING_INTERVAL: "{{ .Values.conf.sqsPollingInterval }}"
  CHECKS_SQS_QUEUE_ARN: "{{ .Values.conf.checksQueueArn }}"
  SCANS_SQS_QUEUE_ARN: "{{ .Values.conf.scansQueueArn }}"
  RESULTS_HOST: "{{ .Values.conf.resultsHost | default (include "resultsHost" .)}}"
  RESULTS_SCHEME: "{{ .Values.conf.resultsScheme }}"
  DEVHOSE_URL: "{{ .Values.conf.devHoseURL }}"
  LEDGER_SOURCE: "{{ .Values.conf.ledgerSource }}"
  LEDGER_TENANT: "{{ .Values.conf.ledgerTenant }}"
  DOGSTATSD_ADDR: "{{ .Values.conf.dogstatsdAddr  | default (include "metricsDogstatsdAddr" .)}}"
  REDIS_ADDR: "{{ .Values.conf.redisAddr  | default (include "metricsRedisAddr" .)}}"
