---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "metrics.fullname" . }}-redis
  labels:
    app: {{ include "metrics.fullname" . }}-redis
spec:
  ports:
    - port: 6379
  selector:
    app.kubernetes.io/name: {{ include "metrics.name" . }}-redis
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metrics.fullname" . }}-redis
  labels:
    app: {{ include "metrics.fullname" . }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "metrics.name" . }}-redis
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "metrics.name" . }}-redis
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - image: redis:alpine
          name: redis
          args: ["--requirepass", "$(REDIS_PASSWORD)"]
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "metrics.fullname" . }}
                  key: REDIS_PASSWORD
          ports:
            - containerPort: 6379
              name: redis
