apiVersion: v1
kind: Secret
metadata:
  labels:
    name: {{ include "metrics.fullname" . }}
  name: {{ include "metrics.fullname" . }}
type: Opaque
data:
  LEDGER_TOKEN: {{ .Values.conf.ledgerToken | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.conf.redisPassword | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    name: {{ include "metrics.fullname" . }}-dogstatsd
  name: {{ include "metrics.fullname" . }}-dogstatsd
type: Opaque
data:
  API_KEY: {{ .Values.conf.dogstatsdApiKey | b64enc | quote }}
