apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    name: {{ include "persistence.fullname" . }}
  name: {{ include "persistence.fullname" . }}
data:
  POSTGRES_DB: "{{ .Values.db.name }}"
  POSTGRES_HOST: "{{ .Values.db.host }}"
  POSTGRES_PORT: "{{ .Values.db.port }}"
  POSTGRES_USER: "{{ .Values.db.user }}"
  STREAM_CHANNEL: "{{ .Values.conf.channel }}"
  REGION: "{{ .Values.conf.region }}"
  SCANS_BUCKET: "{{ .Values.conf.s3Scans }}"
  SNS_TOPIC_ARN: "{{ .Values.conf.snsTopic }}"
  AWS_REGION: "{{ .Values.conf.region }}"
  NESSUS_CHECK_QUEUE: "{{ .Values.conf.nessusCheckQueue }}"
  RAILS_MAX_THREADS: "{{ .Values.conf.railsMaxThreads }}"
