{{ if .Values.conf.loadSQL }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    name: {{ include "persistence.fullname" . }}-load
  name: {{ include "persistence.fullname" . }}-load
data:
  load.sql: {{ (tpl .Values.conf.loadSQL . | quote ) }}
{{ end }}
