{{- if .Values.ingress.enabled -}}
{{- $fullName := include "persistence.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "persistence.labels" . | indent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 8m
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ include "persistence.hostname" . }}
      secretName: {{ $fullName }}-tls
{{- end }}
  rules:
    - host: {{ include "persistence.hostname" . }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
{{- end }}
