apiVersion: v1
kind: Secret
metadata:
  labels:
    name: {{ include "persistence.fullname" . }}
  name: {{ include "persistence.fullname" . }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.db.password | b64enc | quote }}
  SECRET_KEY_BASE: {{ .Values.conf.secretKeyBase | b64enc | quote  }}
