{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "persistence.serviceAccountName" . }}
  labels:
{{ include "persistence.labels" . | indent 4 }}
{{- end -}}
