{{- $_ := (set .Values "comp" .Values.insights) -}}
{{- if .Values.comp.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "insights.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
spec:
  {{- if kindIs "int64" .Values.comp.replicaCount }}
  replicas: {{ .Values.comp.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "vulcan.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "vulcan.podLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/insights/config-proxy.yaml") . | sha256sum }}
        prometheus.io/scrape: 'true'
        prometheus.io/port: '{{ .Values.comp.proxy.metricsPort }}'
        {{- with .Values.comp.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        {{- include "common-deployment-sidecars" . | nindent 8 }}
        - name: insights-private
          {{- include "common-container" . | nindent 10 }}
          env:
            - name: AWS_REGION
              value: {{ .Values.comp.conf.region | default (include "region" . ) | quote }}
            - name: ACCESS_LOG
              value: {{ .Values.comp.conf.log | quote }}
            - name: AWS_S3_BUCKET
              value: {{ .Values.comp.conf.private.s3Bucket | quote }}
            - name: STRIP_PATH
              value: {{ .Values.comp.conf.private.prefix | quote }}
            - name: HEALTHCHECK_PATH
              value: "/healthcheck"
            - name: APP_PORT
              value: {{ .Values.comp.containerPort | quote }}
          ports:
            - name: private
              containerPort: {{ .Values.comp.containerPort }}
              protocol: TCP
        - name: insights-public
          {{- include "common-container" . | nindent 10 }}
          env:
            - name: AWS_REGION
              value: {{ .Values.comp.conf.region | default (include "region" . ) | quote }}
            - name: ACCESS_LOG
              value: {{ .Values.comp.conf.log | quote }}
            - name: AWS_S3_BUCKET
              value: {{ .Values.comp.conf.public.s3Bucket | quote }}
            - name: STRIP_PATH
              value: {{ .Values.comp.conf.public.prefix | quote }}
            - name: HEALTHCHECK_PATH
              value: "/healthcheck"
            - name: APP_PORT
              value: {{ add .Values.comp.containerPort 1 | quote }}
          ports:
            - name: private
              containerPort: {{ add .Values.comp.containerPort 1 }}
              protocol: TCP
      volumes:
      {{- include "common-deployment-volumes" . | nindent 6 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.comp.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.comp.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end -}}
