{{- $c := (dict "comp" .Values.insights "context" $) -}}
{{- if $c.comp.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "insights.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/component: insights
spec:
  {{- if kindIs "int64" $c.comp.replicaCount }}
  replicas: {{ $c.comp.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "vulcan.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: insights
  template:
    metadata:
      labels: {{- include "vulcan.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: insights
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/insights/config-proxy.yaml") . | sha256sum }}
        prometheus.io/scrape: 'true'
        prometheus.io/port: '{{ $c.comp.proxy.metricsPort }}'
        {{- with $c.comp.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- include "comp-common-spec" $c | nindent 6 }}
    {{- with $c.comp.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml $c.comp.podSecurityContext | nindent 8 }}
      containers:
        {{- include "comp-common-containers" $c | nindent 8}}
      {{- range $i, $p := $c.comp.conf.proxies }}
        {{- $port := add $c.comp.containerPort $i }}
        - name: "insights-{{ $p.name }}"
          securityContext:
            {{- toYaml $c.comp.securityContext | nindent 12 }}
          image: "{{ $c.comp.image.repository }}:{{ $c.comp.image.tag }}"
          imagePullPolicy: {{ $c.comp.image.pullPolicy }}
          env:
            - name: AWS_REGION
              value: "{{ $c.comp.conf.region | default (include "region" $c.context) }}"
            - name: ACCESS_LOG
              value: "{{ $c.comp.conf.log }}"
            - name: AWS_S3_BUCKET
              value: "{{ $p.s3Bucket }}"
            - name: STRIP_PATH
              value: "{{ $p.prefix }}"
            - name: HEALTHCHECK_PATH
              value: "/healthcheck"
            - name: APP_PORT
              value: "{{ $port }}"
            {{- if $c.context.Values.minio.enabled }}
            - name: AWS_API_ENDPOINT
              value: "{{ include "minioEndpoint" $c.context }}"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: "{{ printf "%s-minio" $c.context.Release.Name  }}"
                  key: access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ printf "%s-minio" $c.context.Release.Name  }}"
                  key: secret-key
            {{- end }}
          ports:
            - name: {{ $p.name }}
              containerPort: {{ $port }}
              protocol: TCP
          {{- if or $c.comp.lifecycle.preStopCommand $c.comp.lifecycle.preStopSleep }}
          lifecycle:
            preStop:
              exec:
          {{- if $c.comp.lifecycle.preStopCommand }}
                command: {{ $c.comp.lifecycle.preStopCommand }}
          {{- else }}
                command: ["/bin/sh","-c","sleep {{ $c.comp.lifecycle.preStopSleep }};"]
          {{- end -}}
          {{- end -}}
          {{- if and $c.comp.readinessProbe.enabled $c.comp.readinessProbe.path }}
          livenessProbe:
            httpGet:
              path: {{ $c.comp.livenessProbe.path }}
              port: {{ $port }}
            initialDelaySeconds: {{ $c.comp.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ $c.comp.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ $c.comp.livenessProbe.timeoutSeconds }}
            successThreshold: {{ $c.comp.livenessProbe.successThreshold }}
            failureThreshold: {{ $c.comp.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if and $c.comp.readinessProbe.enabled  $c.comp.readinessProbe.path }}
          readinessProbe:
            httpGet:
              path: {{ $c.comp.readinessProbe.path }}
              port: {{ $port }}
            initialDelaySeconds: {{ $c.comp.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ $c.comp.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ $c.comp.readinessProbe.timeoutSeconds }}
            successThreshold: {{ $c.comp.readinessProbe.successThreshold }}
            failureThreshold: {{ $c.comp.readinessProbe.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml $c.comp.resources | nindent 12 }}
      {{- end }}
      volumes:
      {{- include "comp-common-volumes" $c | nindent 6}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with $c.comp.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with $c.comp.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end -}}
