{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "scanengine.serviceAccountName" . }}
  labels:
{{ include "scanengine.labels" . | nindent 4 }}
{{- end -}}
