# Default values for vulndb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount:

image:
  repository: adevinta/vulnerability-db
  tag: latest
  pullPolicy: Always

waitfordb:
  image:
    repository: postgres
    tag: 9.6-alpine

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 50

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

conf:
  maxEventAge: 365
  logLevel: "error"
  checksQueueArn: arn:aws:sqs:local:TBD:TBD
  vulnsTopicArn: arn:aws:sns:local:TBD:TBD
  resultsUrl: http://vulcan-results.vulcan.com
  resultsInternalUrl: # http://vulcan-results

db:
  internal: false
  host:
  name: TBD
  user: TBD
  password: TBD
  port: 5432
  sslMode: disable
  ca:

# extraEnv:
#   FOO: BAR

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
