image:
  repository: adevinta/vulcan-ui
  tag: latest
  pullPolicy: Always

  path: /index.html

conf:
  apiUrl: # https://vulcan-api/api/v1/
  docs:
    apiLink: # vulcan API doc
    whitelistingLink: # vulcan scanner IPs
    discoveryLink: # vulcan asset discovery doc
    auditRoleLink: # vulcan AWS audit role doc
  contact:
    email: # vulcan contact email
    slack: # vulcan slack channel

# extraEnv:
#   FOO: BAR
