apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "insights.fullname" . }}
  labels:
    {{- include "insights.labels" . | nindent 4 }}
spec:
  {{- if .Values.replicaCount }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "insights.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "insights.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config-proxy.yaml") . | sha256sum }}
        prometheus.io/scrape: 'true'
        prometheus.io/port: '{{ .Values.proxy.metricsPort }}'
        {{- with .Values.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- include "common-spec" . | nindent 6 }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "insights.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      {{- include "proxy-container" . | nindent 8 }}
      {{- $dot := . }}
      {{- range $i, $p := .Values.conf.proxies }}
        {{- $port := add $dot.Values.containerPort $i }}
        - name: "app-{{ $p.name }}"
          securityContext:
            {{- toYaml $dot.Values.securityContext | nindent 12 }}
          image: "{{ $dot.Values.image.repository }}:{{ $dot.Values.image.tag }}"
          imagePullPolicy: {{ $dot.Values.image.pullPolicy }}
          env:
            - name: AWS_REGION
              value: "{{ $dot.Values.conf.region | default $dot.Values.global.region }}"
            - name: ACCESS_LOG
              value: "{{ $dot.Values.conf.log }}"
            - name: AWS_S3_BUCKET
              value: "{{ $p.s3Bucket }}"
            - name: STRIP_PATH
              value: "{{ $p.prefix }}"
            - name: HEALTHCHECK_PATH
              value: "/healthcheck"
            - name: APP_PORT
              value: "{{ $port }}"
            {{- if $dot.Values.global.minio.enabled }}
            - name: AWS_API_ENDPOINT
              value: "{{ include "minioEndpoint" $dot }}"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: "{{ printf "%s-minio" $dot.Release.Name  }}"
                  key: access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: "{{ printf "%s-minio" $dot.Release.Name  }}"
                  key: secret-key
            {{- end }}
          ports:
            - name: {{ $p.name }}
              containerPort: {{ $port }}
              protocol: TCP
          {{- include "common-lifecycle" $dot | nindent 10 }}
          {{- if $dot.Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: "/healthcheck"
              port: {{ $port }}
            initialDelaySeconds: {{ $dot.Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ $dot.Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ $dot.Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ $dot.Values.livenessProbe.successThreshold }}
            failureThreshold: {{ $dot.Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if $dot.Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: "/healthcheck"
              port: {{ $port }}
            initialDelaySeconds: {{ $dot.Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ $dot.Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ $dot.Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ $dot.Values.readinessProbe.successThreshold }}
            failureThreshold: {{ $dot.Values.readinessProbe.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml $dot.Values.resources | nindent 12 }}
      {{- end }}
      volumes:
      - name: config-proxy
        configMap:
          name: {{ .Release.Name }}-{{ .Chart.Name }}-proxy
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
