{{- if .Values.ingress.enabled -}}
{{- $fullName := include "insights.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "insights.labels" . | indent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "X-Frame-Options: SAMEORIGIN";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "X-Frame-Options: DENY";
      more_set_headers "X-Xss-Protection: 1";
      more_set_headers "Strict-Transport-Security: max-age=31536000; includeSubDomains";
      more_set_headers "Content-Security-Policy: default-src 'none'; script-src 'self' 'unsafe-inline' https://{{ include "insights.hostname" .}} https://www.google-analytics.com; font-src 'self' https://{{ include "insights.hostname" .}}; connect-src 'self' https://{{ include "insights.hostname" .}}; img-src 'self' https://{{ include "insights.hostname" .}} https://www.google-analytics.com; style-src 'self' 'unsafe-inline' https://{{ include "insights.hostname" .}}; object-src 'none'";
  {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ include "insights.hostname" . }}
      secretName: {{ $fullName }}-tls
{{- end }}
  rules:
    - host: {{ include "insights.hostname" . }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
{{- end }}
