apiVersion: v1
kind: Service
metadata:
  name: {{ include "insights.fullname" . }}
  labels:
    {{- include "insights.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.conf.proxies }}
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP
      name: {{ .name }}
  {{- end }}
  selector:
    {{- include "insights.selectorLabels" . | nindent 4 }}
