{{- $_ := (set .Values "comp" .Values.metrics) -}}
{{- if .Values.comp.enabled }}
{{- include "common-manifests" . }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metrics.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/name: metrics
spec:
  {{- if kindIs "int64" .Values.comp.replicaCount }}
  replicas: {{ .Values.comp.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "vulcan.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/name: metrics
  template:
    metadata:
      labels: {{- include "vulcan.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/name: metrics
      annotations:
        {{- include "common-annotations" . | nindent 8 }}
        {{- with .Values.comp.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        {{- include "common-deployment-sidecars" . | nindent 8 }}
        - name: redis
          image: bitnami/redis:6.0.12
          imagePullPolicy: Always
          ports:
          - containerPort: 6379
            name: redis
            protocol: TCP
        - name: {{ .Values.comp.name }}
          {{- include "common-container" . | nindent 10 }}
          env:
          - name: LOG_LEVEL
            value: {{ .Values.comp.conf.logLevel | quote }}
          - name: SQS_POLLING_INTERVAL
            value: {{ .Values.comp.conf.sqsPollingInterval | quote }}
          - name: CHECKS_SQS_QUEUE_ARN
            value: {{ .Values.comp.conf.checksQueueArn | quote }}
          - name: SCANS_SQS_QUEUE_ARN
            value: {{ .Values.comp.conf.scansQueueArn | quote }}
          - name: FINDINGS_SQS_QUEUE_ARN
            value: {{ .Values.comp.conf.findingsQueueArn | quote }}
          - name: RESULTS_HOST
            value: {{ .Values.comp.conf.resultsHost | default (include "results.fullname" .)| quote }}
          - name: RESULTS_SCHEME
            value: {{ .Values.comp.conf.resultsScheme | quote }}
          - name: DEVHOSE_URL
            value: {{ .Values.comp.conf.devHoseURL | quote }}
          - name: DEVHOSE_TENANT
            value: {{ .Values.comp.conf.devHoseTenant | quote }}
          - name: DEVHOSE_METRICS_SOURCE
            value: {{ .Values.comp.conf.devHoseMetricsSource | quote }}
          - name: DEVHOSE_FINDINGS_SOURCE
            value: {{ .Values.comp.conf.devHoseFindingsSource | quote }}
          - name: REDIS_ADDR
            value: "localhost:6379"
          - name: REDIS_PASSWORD
            value: ""
          - name: VULCAN_API
            value: {{ .Values.comp.conf.vulcanApi | default (include "api.url" .) }}
          - name: VULCAN_API_EXTERNAL
            value: {{ .Values.comp.conf.vulcanAPIExternal | quote }}
        {{- include "common-container-envs" . | nindent 10 }}
          envFrom:
          - secretRef:
              name: {{ include "metrics.fullname" . }}
      volumes:
      {{- include "common-deployment-volumes" . | nindent 6 }}
    {{- include "common-deployment-spec" . | nindent 6 }}
{{- end }}
