{{- $_ := (set .Values "comp" .Values.metrics) -}}
{{- if and .Values.comp.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metrics.fullname" . }}
  labels: {{- include "vulcan.labels" . | nindent 4 }}
    app.kubernetes.io/name: metrics
type: Opaque
data:
  DEVHOSE_TOKEN: {{ .Values.comp.conf.devHoseToken | b64enc | quote }}
  VULCAN_API_TOKEN: {{ .Values.comp.conf.vulcanAPIToken | b64enc | quote }}
{{- end }}
