apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    name: {{ include "api.fullname" . }}
  name: {{ include "api.fullname" . }}
data:
  PORT: "{{ .Values.containerPort }}"
  COOKIE_DOMAIN: "{{ .Values.conf.cookieDomain }}"
  PG_HOST: "{{ .Values.db.host }}"
  PG_NAME: "{{ .Values.db.name }}"
  PG_USER: "{{ .Values.db.user }}"
  PG_PORT: "{{ .Values.db.port }}"
  PG_SSLMODE: "{{ .Values.db.sslMode }}"
{{- if .Values.db.ca }}
  PG_CA_B64: "{{ .Values.db.ca | b64enc }}"
{{- end }}
  SAML_MEATADATA: "{{ .Values.conf.saml.metadata }}"
  SAML_ISSUER: "{{ .Values.conf.saml.issuer }}"
  SAML_CALLBACK: "{{ .Values.conf.saml.callback }}"
  SAML_TRUSTED_DOMAINS: {{ .Values.conf.saml.trustedDomains | quote }}
  SCANENGINE_URL: "{{ .Values.conf.scanEngineUrl | default  (include "scanEngineUrl" .) }}"
  SCHEDULER_URL: "{{ .Values.conf.schedulerUrl | default  (include "crontinuousUrl" .) }}"
  SQS_QUEUE_ARN: "{{ .Values.conf.queueArn }}"
  REPORTS_BASE_PATH: "{{ .Values.conf.reports.basePath }}"
  SES_REGION: "{{ .Values.conf.ses.region }}"
  SES_CONFIG_SET: "{{ .Values.conf.ses.configSet}}"
  SES_SUBJECT: "{{ .Values.conf.ses.subject }}"
  SES_FROM: "{{ .Values.conf.ses.from }}"
  SES_CC: "{{ .Values.conf.ses.cc }}"
  PERSISTENCE_HOST: "{{ .Values.conf.persistenceHost | default  (include "persistenceHost" .) }}"
  VULNERABILITYDB_URL: "{{ .Values.conf.vulnerabilityDbUrl }}"
  GA_ID: "{{ .Values.conf.gaId }}"
  S3_PRIVATE_BUCKET: "{{ .Values.conf.s3PrivateBucket }}"
  S3_PUBLIC_BUCKET: "{{ .Values.conf.s3PublicBucket }}"
  PERSISTENCE_ENDPOINT: "{{ .Values.conf.persistenceEndpoint  | default  (include "persistenceEndpoint" .)}}"
  RESULTS_ENDPOINT: "{{ .Values.conf.resultsEndpoint | default  (include "resultsEndpoint" .)}}"
  PROXY_ENDPOINT: "{{ .Values.conf.proxyEndpoint }}"
  VULCAN_UI: "{{ .Values.conf.vulcanUi }}"
  VIEW_REPORT: "{{ .Values.conf.viewReport }}"
  ENSURE_HEIMDALL: "{{ .Values.conf.ensureHeimdall }}"
