name: Test

on: push

env:
  CT_CHART_DIRS: stable

jobs:
  lint-test:

    strategy:
      fail-fast: false
      matrix:
        k8s:
          - "1.19.16"
          - "1.25.9"
          - "1.26.4"
          - "1.27.2"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Test
        env:
          KVERSION_LIST: ${{ matrix.k8s }}
        run: ./test.sh 1

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Run chart-testing (lint)
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          ct lint --check-version-increment=false

      - name: Run chart-testing (list-changed)
        id: changed
        run: |
          since=$(git describe --tags --abbrev=0 || git rev-list --max-parents=0 --first-parent HEAD)
          changed="$(ct list-changed --since "$since")"
          echo "since=$since changed=$changed"
          echo "changed=$changed" >> $GITHUB_OUTPUT
          echo "since=$since" >> $GITHUB_OUTPUT

      - name: Create kind cluster
        if: steps.changed.outputs.changed != ''
        uses: helm/kind-action@v1.8.0
        with:
          node_image: kindest/node:v${{ matrix.k8s }}   # Test against this kubernetes release
          kubectl_version: v${{ matrix.k8s }}

      - name: Install in kind
        if: steps.changed.outputs.changed != ''
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          ct install --since ${{ steps.changed.outputs.since }} \
            --helm-extra-set-args "-f examples/local.yaml --set=metrics.enabled=false --set=api.enabled=false"

  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Build
        env:
          KVERSION: "1.25.9"
        run: ./build.sh 1
