name: Test

on: push

env:
  CT_CHART_DIRS: stable

jobs:
  lint-test:
    strategy:
      matrix:
        k8s: ["1.25.2"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.8.1

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Run chart-testing (lint)
        run: ct lint --check-version-increment=false

      - name: Create kind cluster
        uses: helm/kind-action@v1.7.0
        with:
          node_image: kindest/node:v${{ matrix.k8s }}   # Test against this kubernetes release
        if: steps.list-changed.outputs.changed == 'true'

      - name: Install in kind
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update
          ct install --helm-extra-set-args "-f examples/local.yaml --set=metrics.enabled=false --set=api.enabled=false"
